---
- hosts: localhost
  connection: local
  become: true
  vars:
   local_home: "{{ lookup('env','HOME') }}"
  
  pre_tasks:
    - name: pre-run | update package cache (arch)
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "ArchLinux"
      
    - name: pre-run | update package cache (debian, etc..)
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution == ["Debian", "Ubuntu", "Pop!_OS"]

  tasks:
     - include: tasks/users.yml
     - include: tasks/packages.yml
     - include: tasks/debs.yml
     - include: tasks/snaps.yml
     - include: tasks/flatpacks.yml
     - include: tasks/oh-my-zsh.yml\
     - name: Test if oh-my-zsh is present.
       stat:
         path: "{{ local_home }}/.oh-my-zsh"
       register: ohmyzsh

     - name: Install "oh-my-zsh"
       shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
       when: not ohmyzsh.stat.exists
