---
- hosts: localhost
  connection: local
  become: true
  
  pre_tasks:
    - name: pre-run | update package cache (arch)
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "ArchLinux"
      
    - name: pre-run | update package cache (debian, etc..)
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution == ["Debian", "Ubuntu", "Pop!_OS"]

  tasks:
     - include: tasks/users.yml
     - include: tasks/packages.yml
     - include: tasks/debs.yml
     - include: tasks/snaps.yml
     - include: tasks/flatpacks.yml
     - include: tasks/oh-my-zsh.yml\
