- name: Install Surfshark
  apt:
    deb: https://ocean.surfshark.com/debian/pool/main/s/surfshark-release/surfshark-release_1.0.0-2_amd64.deb
   
- name: Install TeamViewer
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    
- name: Install Parsec
  apt:
    deb: https://builds.parsecgaming.com/package/parsec-linux.deb
