- name: Install the gedit package from flathub for current user
  flatpak:
    name: org.gnome.gedit
    state: present
    method: user

- name: Install Obsidian
  flatpak:
    name: md.obsidian.Obsidian
    state: present
    method: user

- name: Install Zoom
  flatpak:
    name: us.zoom.Zoom
    state: present
    method: user
    
- name: Install Teams
  flatpak:
    name: com.microsoft.Teams
    state: present
    method: user

