- name: install Debian specific packages
  pkg:
    name: 
       - kitty
       - keepassxc
       - latte-dock
       - lshw
       - meld
       - mtr
       - ncdu
       - neofetch
       - net-tools
       - nmap
       - p7zip
       - powerline
       - pwgen
       - qbittorrent
       - ranger
       - redshift
       - remmina
       - screen
       - scribus
       - shotwell
       - speedtest-cli
       - sshuttle
       - snapd
       - telnet
       - tldr
       - tmate
       - tmux
       - tree
       - vim
       - virt-manager
       - wget
       - wine
       - wireshark
    state: latest
