- name: base package install (Generic)
  package:
     name: 
       - ark
       - asciiquarium
       - bleachbit
       - cheese
       - cmatrix
       - curl
       - ettercap
       - figlet
       - filezilla
       - flameshot
       - fontconfig
       - freerdp
       - gimp
       - git
       - gnupg
       - gparted
       - guake
       - htop
       - iftop
       - inkscape
       - ipcalc
       - iperf
       - kitty
       - keepassxc
       - latte-dock
       - lshw
       - meld
       - mtr
       - ncdu
       - neofetch
       - net-tools
       - nmap
       - p7zip
       - powerline
       - pwgen
       - qbittorrent
       - ranger
       - redshift
       - remmina
       - screen
       - scribus
       - shotwell
       - speedtest-cli
       - sshuttle
       - snapd
       - telnet
       - tldr
       - tmate
       - tmux
       - tree
       - vim
       - virt-manager
       - wget
       - wine
       - wireshark
 
- name: install Debian specific packages
  apt:
    name: 
       - openssh-server
       - dnsutils
       - lsb-release
       - vlc
       - wireshark
       - magic-wormhole
       - gdebi
    state: latest
    when: ansible_distribution == ["Debian", "Ubuntu", "Pop!_OS"]

- name: Remove apt packages
  become: yes
  apt:
    name: ['falkon', 'kdeconnect', 'midori', 'kazam']
    state: absent

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: install Arch specific packages
  pacman:
    name: 
       - openssh
       - dnsutils
       - lsb-release
       - vlc
       - wireshark-qt
       - kdiskmark
    state: latest
  when: ansible_distribution == "ArchLinux"

- name: install RHEL specific packages
  dnf:
    name: 
      - openssh-server
      - bind-utils
      - redhat-lsb
      - wireshark
      - kdiskmark
      - magic-wormhole
    state: latest
  when: ansible_distribution == ["CentOS", "Fedora"]
