## PPA for Ubuntu / Debian


# Etcher
- name: ethcher apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61

- apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    state: present
    filename: balena-etcher.list

- name: Update repositories cache and install "etcher" package
  apt:
    name: balena-etcher-electron
    update_cache: yes
    
# Insync
- name: insync apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ACCAF35C

- apt_repository:
    repo: deb http://apt.insync.io/ubuntu $( lsb_release -c | cut -f 2 ) non-free contrib  
    state: present

- name: Update repositories cache and install "etcher" package
  apt:
    name: 
      - insync
      - insync-dolphin
      - insync-nautilus
    update_cache: yes
