- name: add several snap items with --classic tag
  become: yes
  snap:
    name: "{{ item }}"
    classic: yes
  loop:
    - code

- name: Install snap packages
  become: yes
  snap:
    name:
      - bitwarden
      - netdiscover-ondra
      - onlyoffice-desktopeditors
      - authy
      - auto-cpufreq
