flatpaks:
  - com.bitwarden.desktop
  - com.github.tchx84.Flatseal
  - com.moonlight_stream.Moonlight
  - com.prusa3d.PrusaSlicer
  - com.ticktick.TickTick
  - com.usebottles.bottles
  - com.visualstudio.code
  - com.wps.Officecom.wps.Office
  - md.obsidian.Obsidian
  - org.cryptomator.Cryptomator
  - org.onlyoffice.desktopeditors
  - org.yuzu_emu.yuzu
