brew_pkgs:
  # - ansible # Installed via Pip.
  - ansible
  - tmate
  - pwgen
  - vim
  - wget
  - nmap
  - tldr
  - gpg
  - openssl
  - inetutils
  - magic-wormhole
  - sshuttle
  - neofetch
  - matrix
  - curl
  - figlet
  - git
  - exa
  - htop
  - ipcalc
  - iperf3
  - mtr
  - mosh
  - pwgen
  - telnet
  - tree
  - croc
  - yadm
  - cmatrix
  - speedtest-cli
  - pock
  - ncdu
  - watch
  - flameshot
  - bleachbit
  - iterm2
  - appcleaner
  - surfshark
  - mactracker
  - lulu
  - android-file-transfer
  - the-unarchiver
  - vlc
  - teamviewer
  - anydesk
  - calibre
  - maccy
  - powershell
  - screens
  - visual-studio-code
  - powershell
  - obsidian
  - microsoft-remote-desktop
  - bitwarden
  - qbittorrent
  - gawk
  - cryptomator
