# vi:ts=6:sw=2:et:noai:ft=yaml
---
- name: "Apt | Do a dist-upgrade"
  apt:
    upgrade: dist
    force_apt_get: yes
  become: yes
  when: ansible_os_family == 'Debian'

# - name: "Apt | Check if a reboot is required"
#   register: reboot_required_file
#   stat:
#     path: /var/run/reboot-required
#     get_md5: no
#   become: yes
#   when: ansible_os_family == 'Debian'
  
  # doesn't work with ansible-pull
# - name: "Apt | Reboot if kernel updated"
#   reboot:
#     msg: "Reboot initiated by Ansible for kernel updates"
#     connect_timeout: 5
#     reboot_timeout: 300
#     pre_reboot_delay: 0
#     post_reboot_delay: 30
#     test_command: uptime
#   become: yes
#   when: reboot_required_file.stat.exists
#   when: ansible_os_family == 'Debian'

