- name: "Include vars"
  include_vars: main.yml

- name: apt | update repos
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install latest base packages
  ansible.builtin.package:
    name: "{{ generic_packages }}"
    state: present
  # become: yes

- name: Install Croc
  shell: 
    cmd: curl https://getcroc.schollz.com | bash
  when: (ansible_facts['os_family'] == "Debian" and ansible_facts['architecture'] == "x86_64") 
  # become: yes

- name: Install additional Debian pkgs 
  apt:
    name: "{{ debian_packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes
  # become: yes
  when: (ansible_facts['os_family'] == "Debian") 

- name: Install additional Arch pkgs 
  pacman:
    name: "{{ arch_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Archlinux'

# - name: Disable SSH password auth
#   lineinfile:
#     dest: /etc/ssh/sshd_config
#     regexp: "#PasswordAuthentication yes"
#     line: "PasswordAuthentication no"
#   register: sshd_config
#   become: yes

# - name: Enable passwordless sudo for "{{ username }}"
#   lineinfile:
#    dest: /etc/sudoers
#    regexp: "^%wheel"
#    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
#    validate: "/usr/sbin/visudo -cf %s"
#   # become: yes

# - name: Restart SSH daemon only when above variable sshd_config changes
#   service:
#     name: sshd
#     state: restarted
#   # become: yes
#   when: sshd_config.changed

