- name: Install BTRFS packages and dependenciess
  apt:
    pkg:
    - btrfs-progs
    - snapper
    - snapper-gui
    - grub-btrfs
    state: present
    force_apt_get: yes
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: Create the snapper configuration for the root filesystem
  ansible.builtin.copy:
    src: /usr/share/snapper/config-templates/default
    dest: /etc/snapper/configs/root
    owner: root
    group: root

- name: Snapper config
  lineinfile:
    dest: /etc/default/snapper
    regexp: 'SNAPPER_CONFIGS='
    line: 'SNAPPER_CONFIGS="root"'
  become: yes

- name: Prevent "updatedb" from indexing the snapshots, which would slow down the system
  lineinfile:
    dest: /etc/updatedb.conf
    regexp: '# PRUNENAMES'
    line: 'PRUNENAMES = ".snapshots"'
  become: yes

- name: fix grub-btrfs bug with btrfs-progs 6.1.1
  lineinfile:
    path: /etc/grub.d/41_snapshots-btrfs
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: '^(# *)?snap[@]:13(.*)', line: 'snap[@]:12' }
      become: yes

      # local path_snapshot=${snap[@]:13:${#snap[@]}}

