---
# DEBS
- name: Install Parsec deb (only x64)
  apt:
    deb: https://builds.parsecgaming.com/package/parsec-linux.deb
  when: (ansible_facts['os_family'] == "Debian" and ansible_facts['architecture'] == "x86_64") 
