---
- name: Installing Flatpaks
  apt:
    name: flatpak
  # when: ansible_os_family == 'Debian'
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  # when: ansible_os_family == 'Debian'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Flatpaks (system wide)
  flatpak:
    name: "{{ flatpaks }}"
    state: present
  # when: ansible_os_family == 'Debian'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install additional Flatpaks (only x64)
  flatpak:
    name:
     - com.usebottles.bottles
     - org.onlyoffice.desktopeditors
    state: present
  # when: ansible_os_family == 'Debian'
  ignore_errors: "{{ ansible_check_mode }}"
  when: ansible_facts['architecture'] == "x86_64"

  
