---
- name: Installing Flatpaks
  apt:
    name: flatpak
  # when: ansible_os_family == 'Debian'
  become: yes

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  # when: ansible_os_family == 'Debian'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Flatpaks
  flatpak:
    name: "{{ flatpaks }}"
    state: present
  # when: ansible_os_family == 'Debian'
  ignore_errors: "{{ ansible_check_mode }}"
