- name: Install virt-manager and it's dependencies
  apt:
    name:
    - qemu-kvm 
    - libvirt-clients 
    - libvirt-daemon-system 
    - bridge-utils 
    - virtinst 
    - libvirt-daemon 
    - virt-manager
    state: present
    force_apt_get: yes
    update_cache: yes
  # become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Enable and start  virtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes
  # become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Autostart default network
  shell:
    cmd: virsh net-autostart --network default  
  become_user: pacadmin

- name: Add the user to libvirt group
  ansible.builtin.user:
    name: pacadmin
    group: admin

- name: adding to libvirtd
  user:
    name: pacadmin
    groups: libvirt
    append: yes

- name: adding to kvm
  user:
    name: pacadmin
    groups: kvm
    append: yes

# usermod -a -G libvirt $(whoami)  
# usermod -a -G  $(whoami)
